const bingoStrings = [
    { title: "Merge alla cieca", subtitle: "qualcuno fa il merge senza leggere neanche una riga del codice" },
    { title: "Funzionava sulla mia macchina", subtitle: "la classica scusa davanti a un bug incomprensibile" },
    { title: "La riunione infinita", subtitle: "dove si parla tanto ma il problema rimane irrisolto" },
    { title: "Debug mistico", subtitle: "il codice inizia a funzionare senza che nessuno sappia perché" },
    { title: "Il commit misterioso", subtitle: "nessuno sa chi lo ha fatto, ma ora è lì" },
    { title: "Il junior risolve un bug che il senior non ha capito", subtitle: "e tutti fingono che sia normale" },
    { title: "Deadline spostata... di nuovo", subtitle: 'perché ovviamente "ci vuole solo un secondo"' },
    { title: "Spaghetti code", subtitle: "nessuno sa cosa fa, nessuno sa come modificarlo, ma tutti lo temono" },
    { title: "Commenti che dicono il contrario del codice", subtitle: "viva la coerenza" },
    { title: "È solo un quick fix", subtitle: "detto prima di introdurre il bug del secolo" },
    { title: "La card fantasma", subtitle: "è on hold da settimane, nessuno sa più cosa stiamo aspettando" },
    { title: "Il bot per fare la build si spacca", subtitle: "e chi l'ha creato è in ferie" },
    { title: "Branch dimenticato", subtitle: "nessuno lo cancella, nessuno lo usa, ma teniamolo per sicurezza" },
    { title: "Utility function mai richiamate", subtitle: "prima o poi le useremo" },
    { title: "La feature che nessuno voleva", subtitle: "ma ora è in produzione" },
    { title: "Il collega che scrive tutto in una singola linea", subtitle: "e chi lo capisce è un eroe" },
    { title: "Refactor promesso ma mai fatto", subtitle: "perché c'è sempre qualcosa di più urgente" },
    { title: "Il ticket assegnato a tutti, ma risolto da nessuno", subtitle: "pura democrazia" },
    { title: "Il ticket urgente che non prende nessuno", subtitle: "se non scrivo su slack nessuno si accorge di me" },
    { title: "Il ticket very high dalla spagna", subtitle: "ed era un errore in console non bloccante" },
    { title: "La guerra delle dipendenze", subtitle: "aggiornare una libreria e distruggere il progetto" },
    { title: "La build che funzionava fino a cinque minuti fa", subtitle: "nessuno sa cosa è successo" },
    { title: "Questa volta facciamo le cose bene", subtitle: "spoiler: non succederà" },
    { title: "Il codice che richiede un PhD per essere capito", subtitle: "e nessuno ha quel PhD" },
    { title: "Il collega che usa il terminale come se fosse in Matrix", subtitle: "e tutti lo guardano ammirati" },
    { title: "Il check 'temporaneamente' disattivato", subtitle: "ovvero per sempre" },
    { title: "Il fix che introduce un altro bug", subtitle: "ad azione corrisponde reazione" },
    { title: "Il collega che committa direttamente su stable", subtitle: "e tutti trattengono il fiato" },
    { title: "L'approvazione del codice senza leggerlo", subtitle: "Sì, sembra buono!" },
    { title: "Il codice scritto in geroglifici", subtitle: "sembra più un puzzle che un programma" },
    { title: "Dovrebbe essere facile", subtitle: "ultime parole famose prima di settimane di debugging" },
    { title: "Il database che va in timeout proprio ora", subtitle: "e nessuno sa cosa fare" },
    { title: "L'incontro per decidere quando fare il prossimo incontro", subtitle: "pura efficienza" },
    { title: "Il deploy in produzione il venerdì pomeriggio", subtitle: "viviamo la vita un quarto di codice alla volta" },
    { title: "Il ticket urgente del venerdì pomeriggio", subtitle: "fanculo i flussi di lavoro" },
    { title: "Ma nel ticket non c'era scritto!", subtitle: "il mantra del dev disperato" },
    { title: "La documentazione obsoleta", subtitle: "aggiornata l'ultima volta nel 2010" },
    { title: "Il bug che sparisce quando provi a mostrarlo", subtitle: "magia nera" },
    { title: "L'ambiente di sviluppo che smette di funzionare senza motivo", subtitle: "e nessuno sa cosa fare" },
    { title: "Il collega che usa shortcut impossibili", subtitle: "e sembra un hacker di Hollywood" },
    { title: "Il metodo chiamato 'doStuff()'", subtitle: "per chiarezza" },
    { title: "Il 'fix veloce' che richiede ore", subtitle: "perché nulla è mai semplice" },
    { title: "Il collega che dice 'ho un'idea'", subtitle: "e tutti iniziano a preoccuparsi" },
    { title: "Il codice che sembra scritto da un alieno", subtitle: "e nessuno osa modificarlo" },
    { title: "Il collega che dice 'lascia fare a me'", subtitle: "e subito il progetto esplode" },
    { title: "L'IA introduce un bug", subtitle: "e nessuno sa cosa fare per fermarla" },
    { title: "Qualcuno prova a integrare un branch in sviluppo sul quale ha lavorato solo lui", subtitle: "e condanna due branch a morte certa" },
    { title: "Qualcuno dice IABBONE", subtitle: "" },
    { title: "Il collega che dice 'ah ho capito'", subtitle: "ma è l'unico che ha capito" },
    { title: "Qualcuno perde mezz'ora a risolvere problemi fuori dalla lavorazione", subtitle: "" },
    { title: "Tutti guardano una persona che fa codice sulla tv", subtitle: "e nessuno sa di cosa sta parlando" },
]; 

